### PR TITLE
Refactored repository code and commands for running website

### PR DESCRIPTION
**Pull request by Axl4767**

### CODE REVIEW

**Review by Janiel777 — CHANGES_REQUESTED** [review]
## A pull request with compilation problems😑😂
image


I am open to anyone feeling free to organize the project folders and propose a format and organization rules, but I believe that most of the changes that were made here were not properly thought out.

Having moved folders and files from where they were, problems with finding file paths were generated. Next time, make sure to fix the file includes at least. I'm not going to spend more than 5 minutes reviewing this pull request because you didn't even have the trouble of running the project and uploading the code without errors. Even so, I'm going to leave you some questions as feedback so that you can think about them yourself and help you get on track the next time you try to refactor the code.


1. Why is there a src folder outside the api (back end) and outside the ui/client (front end)?

2. Why did you delete the content of gitignore?

3. What does a gitignore file do?

4. Why did you run the npm run build command?

5. What does the npm run buil command do, what does it generate and what is it used for?

6. Why did you delete the package-lock.json and package.json files, what are these used for?

**Comment by Janiel777** [comment]
If you continue working on that branch trying to fix the refactoring, you are going to waste a lot of time. I'm going to close this pull request but if you want to leave a comment you can open it and then close it again. If you still want to work on refactoring, my advice is to start a new branch and forget about this code.

**Comment by Axl4767** [comment]
> If you continue working on that branch trying to fix the refactoring, you are going to waste a lot of time. I'm going to close this pull request but if you want to leave a comment you can open it and then close it again. If you still want to work on refactoring, my advice is to start a new branch and forget about this code.

Sorry if sounding a bit defensive, but I believe your response comes out a bit condescending, brushing off these changes after not bothering for 5 minutes, when it seems you didn't even review the branch.

image

My changes seem to work on my Mac, while the base website at the start did not. Maybe we can pinpoint the error instead of "this is wrong", we are developers, there are things to be learnt either way.

1. Conciseness and being more condensed. The exact order or folders doesn't really matter at the end, I do admit these organizational changes were made more to my preference to what a "readable" repository looks like.
2. I ignored that file but it seems an auto-formatter in my vscode trimmed the file to be only the necessary length. Only a copy&paste issue, don't know why the need to make it a point.
3. Thanks, I know what they do. 
4. Experimentation? Doesn't matter in this context, the build command is inconsequential with the changes made.
5. Once again, thanks for giving some pointers, but in this context it doesn't matter. The refactor's aim was making the repository more clear, easier to read, and migrating from the old class components in javascript to more recent, better supported Functional Components in .jsx files. Any issues with the website organization is really a secondary issue.
6. They were deleted because another package.json was created at the root folder to serve as the file for the whole website. Once again, I implore you to review the changes made. 

Just in case, these comments are not made in any way in bad faith, I just think my changes were ignored by some unrelated issues,

**Comment by Janiel777** [comment]
Volviendo a revisar tu codigo aun noto que lo de crear archivos css para separar el codigo css del codigo js, solamente lo hiciste para el index.js y para el app.js. Sin embargo en el index.js importaste el index.css pero en el app.js no importaste el app.css. Esto me da a entender el el archivo app.css no se esta usando. Ademas de solo crear un archivo .css para estos dos archivos, me gustaria que crearas un archivo .css para cada componente o archivo que tenga atributos css en el para mantener el codigo mas organizado. Me gustaria que documentes el formato en el que estas organizando el proyecto. Con esto me refiero a que crees una serie de instrucciones que deberia de seguir cada desarrollador para todos utilizar el mimso formato. Por ejemplo definir que carpeta contiene el back end, que carpeta contiene el front. Crear carpetas que puedan ser utilizadas para guardar logos, imagenes, sonidos, videos, los componentes etc. Crear una regla que diga que cada vez que se cree un componente de react, tambien se cree un archivo css para este mismo y en que formato se escribe el codigo css ya que existen muchas maneras de hacerlo. Estas reglas se pueden subir al readme file principal para que cada developer siga el mismo formato en todo los tasks.

**Pull request closed without merging**
