### PR TITLE
Added input verification for sign up form.

### LINKED ISSUE #56: Validation and Error Handling
- [x] Develop validation rules for each form to ensure the accuracy and completeness of the data entered (e.g., date formats, mandatory fields).
- [x] Implement user-friendly error messages and prompts to correct any invalid inputs before submission.

### PR DESCRIPTION
**Pull request by gabrielpadilla7**
Sign up form now has input verification. If approved, closes #56 as it is complete.

### CODE REVIEW

**Review by JeremySanchez1 — CHANGES_REQUESTED** [review]
Excellent work, pretty robust implementation!

The only feedback and request I would like to add is for phone numbers to be limited to only 10 numbers.

**Comment by gabrielpadilla7** [comment]
> Excellent work, pretty robust implementation!
> 
> The only feedback and request I would like to add is for phone numbers to be limited to only 10 numbers.
> 

On it! I'll work on this in a bit.

**Comment by gabrielpadilla7** [comment]
@JeremySanchez1 change has been made, please test and let me know if there's any other case that needs to be implemented

**Review by JeremySanchez1 — COMMENTED** [review]
Looks great :)

**Review by JeremySanchez1 — APPROVED** [review]
Approved changes

**Comment by gabrielpadilla7** [comment]
Merging as it has been approved

**Pull request merged**
