### PR TITLE
Task #8 - Implemented the base of the User cmpnt and its properties

### PR DESCRIPTION
**Pull request by PinkSylvie**
Implemented the Base of UserContext, its parameters as discussed with the leader of the Data Entry Team, those being:
 * {number} id - The id of the user.
 *  {string} frst_name - The first name of the user.
 * {string} middle_initial - The middle name's initial of the user. (optional)
 *  {string} frst_lst_name - The first lastname of the user.
 *  {string} scnd_lst_name - The second last name of the user. (optional)
 *  {number} phone_num - The phone number of the user.
 *  {string} profile - The profile URL of the user. (optional)
 * {string} usr_name - The user_name of the user.
 *  {string} email - The email of the user.
 *  {string} password - The password of the user.

A user is created in the UserContext and using useUser in the components you want to use it you can access it everywhere in the web page
image
image

I left h1 tests in the Taskform and TaskList files so you can see how it works. You can easily find them using Ctrl+F to look for TEST

### CODE REVIEW

**Comment by Janiel777** [comment]
Hello @PinkSylvie,

First of all, I want to thank you for the commitment and effort you have put into developing the User component.

After reviewing the pull request, I wanted to share some observations that led me to think that some adjustments to your pull request would be necessary.

I notice that you used react-native elements like Text and Image, these are intended for mobile applications and would not render properly in a web environment. I know it's confusing and I admit that I didn't know they were different things either because they have practically the same name, React Native is used for mobile application development and React is used for web application development.

Also, I think that this component is very simple, I don't know if you can work a little more on the visualization. Remember that the purpose of this issue is to design how the user's information will be seen once the user logs in. This component can be used in areas such as a profile section, which displays user information. So it should be recommended that it have some CSS code.

Additionally, as it says in the issue, it may be reusable in other sections so I do not think it is advisable to show compromising information such as the user's password. The issue does not explain exactly what other sections it will be displayed in, so in reality, you do have the freedom to display the password and user information in the way you want.

Conclusion:
1. Don't use react native
2. Improve the visualization of the component further. If it is possible for you to run the code showing a screenshot of what the component would look like, that would be great.

**Comment by PinkSylvie** [comment]
@Janiel777 I'll keep your comments in mind when fixing the code a bit to eliminate react native but I don't think I can visualize much with this user component. It's supposed to be a class that stores the user data from the SQL, when it's created it receives the data to create a user object wherever it needs to have that data easily accessible with the getters, and easily changeable with the setters (which need to be updated with SQL integration so that it updates the change on the database as well, which again should be another task)like the profile or the template. Visualizing a user would be another task more akin to the profile page which would use the data and the getters to visualize the user.

**Comment by Janiel777** [comment]
Now I'm confused, I see you made two commits. Forgive my confusion, in one commit you made a javascript class but in the next commit you corrected it, deleted the class and replaced it with a react component?

**Comment by PinkSylvie** [comment]
@Janiel777 The most recent is the JavaScript class. I was tinkering around seeing which one I could do and understand best.

**Comment by Janiel777** [comment]
First of all, you don't need to save the information in a class because that's what the database is for, to save data. What you did there is not a react component. A react component is not for storing information. A react component is purely displaying information that may or may not be interactive.

So to be clear, the last commit you made is this: class User{
     constructor(id, frst_name, middle_initial, frst_lst_name, scnd_lst_name, phone_num, profile, usr_name, email, password){
         this.id = id;
         this.frst_name = frst_name;
         this.middle_initial = middle_initial;
         this.frst_lst_name = frst_lst_name;
         this.scnd_lst_name = scnd_lst_name;
         this.phone_num = phone_num;
         this.profile = profile;
         this.usr_name = usr_name;
         this.email = email;
         this.password = password;
     }
     getId() {
         return this.id;
     }
     setId(value) {
         this.id = value;
     }
     getFirstName() {
         return this.frst_name;
     }
     setFirstName(value) {
         this.frst_name = value;
     }......

Because if so, then that is not a react component. A react component has to be code written in javascript that returns an HTML tag. The mix and syntax of these two is usually called jsx.

**Comment by PinkSylvie** [comment]
@Janiel777 I'm just doing what I was told in my task description #8, I was told to make the base of the user and have it with getters and setters

**Comment by Janiel777** [comment]
This piece of code is a react component because it takes information as a parameter and shows it through labels.
```
const User = ({ id, frst_name, middle_initial, frst_lst_name, scnd_lst_name, phone_num, profile, usr_name, email, password }) => (
     <h1>
         <Text>{id}</Text>
         <Text>{frst_name}</Text>
         <Text>{middle_initial}</Text>
         <Text>{middle_initial}</Text>
         <Text>{frst_lst_name}</Text>
         <Text>{scnd_lst_name}</Text>
         <Text>{phone_num}</Text>
         <Text>{usr_name}</Text>
         <Text>{email}</Text>
         <Text>{password}</Text>
         <Image source={{uri: profile}}
         />
     </h1>
   );
   export defaultUser;
```

**Comment by PinkSylvie** [comment]
@Janiel777 But that has no getters and setters which I was told to add in my task description

**Comment by Janiel777** [comment]
I think that the getters and setters thing is poorly planned, that issue needs better planning.

**Comment by PinkSylvie** [comment]
@Janiel777 Ya subi el commit con el UserContext, aunque me esta dando un conflict raro aqui en github
Pero al menos asi es como se ve:
image
image

**Comment by Janiel777** [comment]
Le hiciste pull antes de hacer el push?

**Comment by Janiel777** [comment]
Sospecho que no lo histe por que estoy viendo cambios que yo subi en un commit que no estan en tu branch. Por ejemplo:
```javascript
 const response = await fetch('http://localhost:4000/tasks')
```
Esas lineas de codigo que hacen fetch usando el url de local host, en el codigo que yo subi estan asi:
```javascript
const response = await fetch(`${process.env.REACT_APP_BACKEND_URL}/tasks`)
```

**Comment by PinkSylvie** [comment]
Es que para que aparezcan le tengo que hacer pull a mi main y luego al branch

**Comment by PinkSylvie** [comment]
Porque el main no está up to date

**Comment by Janiel777** [comment]
A que te refieres con que no esta actualizado?

**Comment by Janiel777** [comment]
Ese conflicto con el archivo .env lo resuelvo ya mismo pero en realidad se supone que los archivos .env no se muestre en el repo. Al parecer, aunque los archivos .env estan incluidos en el .gitignore, este como quiera se actualiza en el repo. Creo que estos se debe a que como ya existia un archivo .env inicialmente que yo subi con el codigo base como ejemplo para que entendieran que tenia que incluir el mismo, este se sigue actualizando aunque este en el .gitignore.

**Comment by Janiel777** [comment]
Al parecer cuando resolvi el conflicto que habia en el archivo .env, el main y el branch se unieron correctamente. Se ve que implementaste correctamente el userContext y se ven las propiedades que le diste al usuario. Ademas se ve claramente que para acceder en la informacion del usuario en cualquier componente de la aplicacion basta con importar el useUser en el archivo deseado y definirlo dentro del componente.

importarlo:
```javascript
import { useUser } from './UserContext';
```

definirlo:
```javascript
const { user, setUser } = useUser();
```

acceder a el mediante:
```javascript
{user.name} {user.middle_initial} {user.frst_lst_name}
```

Segun veo en tus screenshots, todo lo que hiciste de tu task te compilo sin errores. Asi que voy a proceder a hacerle merge al main.

**Review by Janiel777 — COMMENTED** [review]
It is clearly seen that to access user information in any application component, simply import useUser to the desired file and define it inside the component.

import it:

import {useUser} from './UserContext';
define it:

const {user, setUser} = useUser();
access it through:

{user.name} {user.middle_initial} {user.frst_lst_name}

I already run this commit locally and everything seems correct.

**Pull request merged**
