### PR TITLE
Button functionality added

### LINKED ISSUE #119: Start your Resume button functionality
Implement the functionality of the button to start your resume. This must trigger the personal information data entry page. 

Suggested priority and difficulty

Priority: P0
Difficulty: 3

### PR DESCRIPTION
**Pull request by gabrielpadilla7**
Button now has functionality. Please verify if it is going to the page that is supposed to go. If it does, completing the pull request closes #119. Forgot to mention that a basic landing page is set up, however it is very basic and not styled for now.

### CODE REVIEW

**Comment by gabrielpadilla7** [comment]
There apparently is a merge conflict. I have no idea how to fix this though, if there is a way to do so please let me know or else I'll re implement

**Comment by gabrielpadilla7** [comment]
Merge conflict fixed

**Comment by gabrielpadilla7** [comment]
updated description

**Review by irsaris — APPROVED** [review]

**Comment by gabrielpadilla7** [comment]
Closing pull request, as the new pull request I will do have these exact changes

**Pull request closed without merging**
